name: Deploy Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "scripts/**"
jobs:
  build-deploy:
    concurrency: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
      - name: Build Site
        run: make build
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./public
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: owen # e.g. 'my-project'
          directory: ./public # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

